version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  nodeWbsSNS:
    container_name: nodeWbsSNS
    build:
      context: ./
    hostname: nodeWbsSNS
    networks:
      - docker_network
    ports:
      - 10200:3000
      - 10100:4000
    links:
      - postgres:app_db
    environment:
      VERSION: v1
      DB_USER: table_admin
      DB_PASSWORD: HeLLo!1
      DB_HOST: app_db
      DB_PORT: 5432
  postgresWbsSNS:
    container_name: postgresWbsSNS
    build:
      context: ./cmd/db
    volumes:
      - <<: *services-volume
        source: ${HOST}/postgresWbsSNS
        target: /var/lib/postgres
    expose:
      - 5432
    hostname: app_db
    networks:
      - docker_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: weather_based_SNS
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${USERPWD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
