version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  node_wbssns:
    container_name: node_wbssns
    build:
      context: ./
    hostname: node_wbssns
    networks:
      - docker_network
    ports:
      - 10200:10200
      - 10100:10100
        #links:
        #- postgres_wbssns:app_db
    environment:
      VERSION: v1
      #DB_USER: table_admin
      #DB_NAME: weather_based_SNS
      #DB_PASSWORD: ${USERPWD}
      #DB_HOST: app_db
      #DB_PORT: 5432
      #postgres_wbssns:
      #container_name: postgres_wbssns
      # build:
      #context: ./cmd/db
      #volumes:
      #- <<: *services-volume
      #source: ${HOST}/postgresWbssns
      #target: /var/lib/postgres
      #expose:
      #- 5432
      #hostname: app_db
      #networks:
            #- docker_network
        #environment:
      #PGDATA: /var/lib/postgresql/data
      # POSTGRES_DB: weather_based_SNS
      #POSTGRES_HOST_AUTH_METHOD: trust
      #POSTGRES_USER: table_admin
      #POSTGRES_PASSWORD: ${USERPWD}
      #POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
